export const FETCH_NBAPLAYERDETAILS_REQUEST = "FETCH_NBAPLAYERDETAILS_REQUEST";
export const FETCH_NBAPLAYERDETAILS_SUCCESS = "FETCH_NBAPLAYERDETAILS_SUCCESS";
export const FETCH_NBAPLAYERDETAILS_FAILURE = "FETCH_NBAPLAYERDETAILS_FAILURE";